### PR TITLE
update script eggs-install.sh

### PR DESCRIPTION
**Pull request by pieroproietti**
I think your script in this way is better.

Run in once and after just use eggs commands.

I think for your system to use --release flag in produce for the release. In that way on the installed system will be removed both calamares and eggs.

### CODE REVIEW

**Comment by aosucas499** [comment]
Yesterday I don't know way but it was necessary to copy user.yaml in /etc/🐧/... And not only in /usr/lib/🐧...

**Comment by aosucas499** [comment]
I'll try with this code. Thanks!

**Comment by aosucas499** [comment]
At the end It worked, I copied some of your recomendations and order of eggs commands.
It worked well with eggs 9.3.7, so if you want and taking into account that I modify some pictures from the theme you have in eggs 9.3.8, I need to do another theme too for the [slim](https://github.com/aosucas499/guadalinex/tree/slim) version of educaandos, and so you dont have so much KB from pictures, I think is better you discard version 9.3.8, don't include my theme and here you have the definitive script to build or incorporate a theme in eggs.

**Comment by aosucas499** [comment]
And if you want my help with your idea to write down instructions for people want to use eggs to develop their distro, I'm here for whatever you need. Thank you so much for your amazing job and time.

**Comment by pieroproietti** [comment]
Thanx Andres!

Today I'm really busy, but soon we will start to write something about
themes and so on.

Have a great day, for me today is great enought: we get marry with Teresa!



Il mar 15 nov 2022, 21:56 aosucas499 ***@***.***> ha scritto:

**Comment by aosucas499** [comment]
Great!!!! Congratulations!!! Enjoy a lot and disconnect from projects. Thank you for everything

**Pull request closed without merging**
